@startuml
object magic_box{
components
shopping list
next_to_do
}

object to_do{
+Schaöltplan abändern
+Bewegungsmelder ausprobieren
+Aktuator an Prototyp dranschrauben
+Code für Bewegungsmelder, RFID, ESP Interaktion schreiben
}

object stores{
BerryBase
Fundoino
Otronic
Amazon
}

object shopping_list_private{
Platinenhalter
helfende Arme
Kabel (ausgerechnet mit Querschnittsrechner)
}

magic_box *-- to_do
magic_box *-- shopping_list_private
shopping_list_private ..> stores :Sources of Supply

@enduml

