@startuml

object component_architecture{
-brain
-worker
-intermediaries
-power generation, storage, managment
}

object Komposition{
+Das Gehirn: Esp32

+Der Arbeiter:
Gasdruckfeder (Öffnungsmechanismus)
Servo (Schließmechanismus)
(Initialisierungsmechanismus)

Optional:
Elektromagnetisches Schnappschloss (nur benötigt, falls die Kiste ein permanent aufstrebenden Öffnungsmechanismus haben soll)

+Intermediäre:
Treiber (zwischen Servo und ESP)
RFID Technologie (User Interaction)
SolarPowerManager (Angelpunkt für Regelung der Strom, Spannungsversorgung )

+Stromversorgung
}

object Komponenten{
-Aufwickelrolle
-(Umlenk/Seilrolle) Rolle
-Robustes Seil
}

object power_management{
+(Producer): solarpanel
+(Intermediate between storage, producent and clients): solar power manager modul
+(Energie Storage): batteries
}

object shopping_list{
+preferred
-cheaper alternative

price range: [70-120] [eu]

+ESP32 USB-C WROOM 4 MB Devkit V1 Board mit WLAN, Bluetooth und Dual-Core-Prozessor (OT1011) (Otronik)
+Breakout-Board für ESP32 Devkit V1 mit Schraubklemmen (Otronik)
+Mikro Linearantrieb / Hubstange, 8mm Ø, 3~5mm/s, 3-6V - 30 bis 130mm Hub (Funduino)
-Servo + servoarm + Verlängerung (Günstiger als der Linear Aktuator)
-HG7881 (L9110S) H-Brücke/Motortreiber mit zwei Kanälen (Verbinndung zwischen Linearaktuator und ESP) (Funduino)
+Die Batterie+Batteriehalter+Batterie18650 (BerryBase)
-Ladeplatine für 3,7V LiIon / LiPo Akkus, mit Ausgang, USB Type C Buchse > Lötpads, 1000mA (BerryBase) (günstigere Alternative, falls Projekt günstiger werden soll)
+Waveshare Semi-flexibles Polykristallines Silizium-Solarpanel, DC5521, 5V USB-Ausgänge, 18V, 10W (BerryBase)
+Waveshare Solar Power Manager Modul D, 5V/3A, USB-C, für 6V-24V Solarpanels, ohne Batteriehalter(Teurere Version, keine Probleme mit Spannungsversorgung)
}


component_architecture *-- Komposition
component_architecture *-- power_management
component_architecture *-- shopping_list
shopping_list ..> stores :Sources of Supply

@enduml